version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=${ACCEPT_EULA}
    ports:
      - "1433:1433"
    networks:
      - shopping-net
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  server:
    build: ./server
    container_name: shopping-server
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=${MODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - shopping-net

  client:
    build: ./client
    container_name: shopping-client
    ports:
      - "5173:80"
    networks:
      - shopping-net
    depends_on:
      - server

networks:
  shopping-net:
    driver: bridge
