version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - shopping-net
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433'"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

  server:
    build: ./server
    container_name: shopping-server
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASS: YourStrong!Passw0rd
      DB_NAME: ShoppingList
    networks:
      - shopping-net

networks:
  shopping-net:
    driver: bridge
